FROM llavina/supervisord

MAINTAINER Luis Lavina "https://github.com/chojayr"

RUN apt-get update

RUN apt-get install -y openjdk-7-jdk

RUN update-alternatives --display java

ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64

